version: '3.8'

networks:
  example:
    driver: bridge

services:
  reverse-proxy:
    container_name: example-nginx
    image: nginx:1.21-alpine
    depends_on:
      - example-api
      - example-client
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '7000:80'
    networks:
      - example
      
  example-client:
    container_name: example-client
    image: example-client
    build:
      context: ./example-client
    depends_on:
      - example-api
    networks:
      - example
    restart: on-failure

  example-api:
    container_name: example-api
    image: example-api
    build:
      context: ./example-api
    networks:
      - example
    restart: on-failure