version: '3.8'
services:
  reverse-proxy:
    image: nginx:1.21-alpine
    depends_on:
      - example-api
      - example-client
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
      
  example-client:
    image: example-client
    build:
      context: ./example-client
    depends_on:
      - example-api
    # It is better to expose apps via reverse proxy
    # ports:
    #   - '4200:80'
    restart: on-failure

  example-api:
    image: example-api
    build:
      context: ./example-api
    # It is better to expose apps via reverse proxy
    # ports:
    #   - '5001:5001'
    restart: on-failure
